$ErrorActionPreference = "Stop"

Add-Type -Path "bin\ExcelDna.Integration.dll"
Add-Type -Path "bin\Microsoft.Web.WebView2.Core.dll"
Add-Type -Path "bin\Microsoft.Web.WebView2.WinForms.dll"
Add-Type -Path "bin\LeeExcel.dll"

Write-Host "=== Verify LeeExcel Core Features ===" -ForegroundColor Cyan

# 1. Verify ScriptManager
Write-Host "`n1. Test ScriptManager save and list..."
$err = ""
$vbaCode = "Sub AutoTest()`n    ActiveSheet.Range(""A1"").Value = 123`nEnd Sub"
$ok = [LeeExcel.ScriptManager]::SaveScript("AutoTestScript", $vbaCode, "Generated by PoC test suite", [ref]$err)

if ($ok) {
    Write-Host "   [Pass] Script saved to %AppData%\LeeExcel\Scripts\AutoTestScript.bas" -ForegroundColor Green
} else {
    Write-Host "   [Fail] Script save failed: $err" -ForegroundColor Red
}

$scripts = [LeeExcel.ScriptManager]::ListScripts()
Write-Host "   Total scripts in storage: $($scripts.Count)"
foreach ($s in $scripts) {
    Write-Host "   - Script: $($s.name) | Desc: $($s.description) | Created: $($s.createdAt)"
}

# 2. Verify NativeBridge dispatch
Write-Host "`n2. Test NativeBridge dispatching..."
$req = '{"action":"list_scripts"}'
$res = [LeeExcel.NativeBridge]::Dispatch($req, $null)
Write-Host "   [Pass] NativeBridge response: $res" -ForegroundColor Green

# 3. Verify SimpleJson
Write-Host "`n3. Test SimpleJson..."
$testObj = [LeeExcel.SnapshotItem]@{
    id = "test_snap_1"
    timeDisplay = "10:45:00"
    fileName = "test.xlsx"
    promptSummary = "Test Summary Prompt"
}
$json = [LeeExcel.SimpleJson]::Serialize($testObj)
Write-Host "   [Pass] SimpleJson serialized: $json" -ForegroundColor Green

# 4. Verify ParseFlatObject with user's complex VBA code containing multiple quotes
Write-Host "`n4. Test ParseFlatObject with complex VBA..."
$rawJsonPayload = '{"action":"execute_vba","code":"Sub RunTask()\r\n    With ws.Range(\"D23\")\r\n        .Value = 1\r\n    End With\r\n    ws.Range(\"N1\").Value = \"abc\"\r\nEnd Sub","prompt":"99乘法表"}'
$parsedDict = [LeeExcel.SimpleJson]::ParseFlatObject($rawJsonPayload)

if ($parsedDict.ContainsKey('code') -and $parsedDict['code'].Contains('End Sub') -and $parsedDict['code'].Contains('Range("D23")')) {
    Write-Host "   [Pass] Successfully parsed user VBA containing multiple quotes without truncation!" -ForegroundColor Green
    Write-Host "   Parsed code: $($parsedDict['code'])" -ForegroundColor Green
} else {
    Write-Host "   [Fail] ParseFlatObject failed or truncated the code!" -ForegroundColor Red
    exit 1
}

Write-Host "`n=== ALL CORE TESTS PASSED SUCCESSFULLY! ===" -ForegroundColor Green

