// test_regex_counter_example.cjs - Demonstrating why Regex.Replace is fundamentally flawed for VBA target binding

console.log("=== Counter-Examples: Demonstrating Flaws in Regex.Replace Binding ===");

const targetWbName = "Sales_2026.xlsx";

function legacyRegexTransform(vbaCode) {
  let finalCode = vbaCode.replace(/\bThisWorkbook\b/gi, `Application.Workbooks("${targetWbName}")`);
  finalCode = finalCode.replace(/\bActiveWorkbook\b/gi, `Application.Workbooks("${targetWbName}")`);
  return finalCode;
}

let passCount = 0;

// Counter-Example 1: String Literal Corruption
const sample1 = `Sub ReportInfo()
    Dim msg As String
    msg = "Generated by ThisWorkbook module version 1.0"
    Range("A1").Value = msg
End Sub`;

const transformed1 = legacyRegexTransform(sample1);
console.log("\n[Counter-Example 1: String Literal]");
console.log("Original:\n" + sample1);
console.log("\nLegacy Transformed:\n" + transformed1);

if (transformed1.includes('Generated by Application.Workbooks("Sales_2026.xlsx") module version 1.0')) {
  console.log("-> EVIDENCE CONFIRMED: String literal content was corrupted by Regex.Replace! Double quotes collide inside string literal.");
  passCount++;
}

// Counter-Example 2: Comment Corruption
const sample2 = `Sub ProcessData()
    ' Note: ActiveWorkbook must be verified before proceeding
    Dim total As Double
End Sub`;

const transformed2 = legacyRegexTransform(sample2);
console.log("\n[Counter-Example 2: Code Comments]");
console.log("Original:\n" + sample2);
console.log("\nLegacy Transformed:\n" + transformed2);

if (transformed2.includes("' Note: Application.Workbooks(\"Sales_2026.xlsx\") must be verified")) {
  console.log("-> EVIDENCE CONFIRMED: Code comments were erroneously altered by Regex.Replace.");
  passCount++;
}

// Counter-Example 3: Double Application Collision (Application.ActiveWorkbook)
const sample3 = `Sub CheckApp()
    Dim name As String
    name = Application.ActiveWorkbook.Name
End Sub`;

const transformed3 = legacyRegexTransform(sample3);
console.log("\n[Counter-Example 3: Application.ActiveWorkbook]");
console.log("Original:\n" + sample3);
console.log("\nLegacy Transformed:\n" + transformed3);

if (transformed3.includes('Application.Application.Workbooks("Sales_2026.xlsx")')) {
  console.log("-> EVIDENCE CONFIRMED: Redundant Application.Application syntax error created by Regex.Replace.");
  passCount++;
}

console.log(`\nAll ${passCount} counter-examples successfully demonstrated.`);
